org: martinez30
app: baby-serverless
service: baby-serverless
frameworkVersion: '3'

custom:
  relatoriosBucket: '${self:service}-${self:provider.stage}-relatorios-bucket-paulo-${self:provider.region}'
  folder_bucket: '${param:folder_bucket, "relatorios"}/'

provider:
  name: aws
  profile: aluno_1
  runtime: nodejs14.x
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-2'}
  environment:
    NOME_DESTINATARIO: ${param:NOME_DESTINATARIO}
    EMAIL_DESTINATARIO: ${param:EMAIL_DESTINATARIO}
    EMAIL_HOST_SMTP: ${param:EMAIL_HOST_SMTP}
    SENHA_HOST_SMTP: ${param:SENHA_HOST_SMTP}

functions:
  onUpload:
    handler: src/functions/uploadS3.onUpload
    events:
      - s3:
          bucket: ${self:custom.relatoriosBucket}
          event: s3:ObjectCreated:*
          rules:  
            - prefix: ${self:custom.folder_bucket}
            - suffix: .xls
      - s3:
          bucket: ${self:custom.relatoriosBucket}
          event: s3:ObjectCreated:*
          rules:  
            - prefix: ${self:custom.folder_bucket} 
            - suffix: .csv
      - s3:
          bucket: ${self:custom.relatoriosBucket}
          event: s3:ObjectCreated:*
          rules:  
            - prefix: ${self:custom.folder_bucket} 
            - suffix: .xlsx
    
